### ISSUE TITLE
[不具合] 終了後メーター

### ISSUE THREAD

**Issue by kotmw0701** [kotmw0701/Splatoon-in-Minecraft-Rewrite#2]
メーター表示でエラーを吐く場合がある

**Comment by kotmw0701** [comment]
以下確認エラー
パーセントの出力表示がNaNになる
> [03:31:10] [Server thread/INFO]: NaN
> [03:31:10] [Server thread/WARN]: [Splatoon_in_Minecraft] Task #4944 for Splatoon_in_Minecraft v0.9.15 generated an exception
> java.lang.StringIndexOutOfBoundsException: String index out of range: -2
>	at java.lang.String.substring(Unknown Source) ~[?:1.8.0_131]
>	at jp.kotmw.splatoon.maingame.threads.ResultRunnable.MeterText2(ResultRunnable.java:62) ~[?:?]
>	at jp.kotmw.splatoon.maingame.threads.ResultRunnable.run(ResultRunnable.java:38) ~[?:?]
>	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
>	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
>	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:738) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
>	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
>	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
>	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
>	at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]

**Comment by kotmw0701** [comment]
ブロックカウント部分の不具合を確認
修正済み
