### ISSUE TITLE
[不具合] 一切塗らない時のエラー

### ISSUE THREAD

**Issue by kotmw0701** [kotmw0701/Splatoon-in-Minecraft-Rewrite#5]
以下のエラー
```
[12:26:16] [Server thread/WARN]: [Splatoon_in_Minecraft] Task #2471 for Splatoon_in_Minecraft v1.3.0 generated an exception
java.lang.StringIndexOutOfBoundsException: String index out of range: -2
	at java.lang.String.substring(String.java:1967) ~[?:1.8.0_65]
	at jp.kotmw.splatoon.maingame.threads.ResultRunnable.MeterText2(ResultRunnable.java:57) ~[?:?]
	at jp.kotmw.splatoon.maingame.threads.ResultRunnable.run(ResultRunnable.java:39) ~[?:?]
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.10.2.jar:git-Spigot-078e2f8-9ff3d7f]
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.10.2.jar:git-Spigot-078e2f8-9ff3d7f]
	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:723) [spigot-1.10.2.jar:git-Spigot-078e2f8-9ff3d7f]
	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.10.2.jar:git-Spigot-078e2f8-9ff3d7f]
	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [spigot-1.10.2.jar:git-Spigot-078e2f8-9ff3d7f]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [spigot-1.10.2.jar:git-Spigot-078e2f8-9ff3d7f]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_65]

```

**Comment by kotmw0701** [comment]
1.3.1にて修正
